language: r
sudo: false
cache: packages
dist: trusty

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      before_cache: Rscript -e 'remotes::install_cran("pkgdown");remotes::install_github("ropenscilabs/rotemplate")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
      env: R_CODECOV=true
    - os: linux
      r: devel
      # env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

r_binary_packages:
  - covr

addons:
  apt:
    packages:
      - libpoppler-cpp-dev

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: iUbodhwdTWY/Lu+u0THafzSCMB+5im7XCYEAoIxNB61KSD0i99e+reqKXy2c5Rh8XS4KqlhOZ7FN0ivJ9T0DU1sIN27cyIZJHwDL3sY2tKsPlrxATM07+WVuVhvHVeF8JGktbI/mHspoI1OSzAoPZsj7LUdWyDIGYNGwYNXqt04=
